language: go

sudo: required

install: 
    - npm install gulp
    - npm install gulp-cssmin
    - npm install gulp-rename
    - npm install event-stream
    - npm install gulp-htmlmin
    - npm install gulp-uglify
    - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17_Linux-64bit.tar.gz
    - tar zxvf hugo_0.17_Linux-64bit.tar.gz
    - mkdir -p $HOME/bin
    - mv hugo_0.17_linux_amd64/hugo_0.17_linux_amd64 $HOME/bin/hugo
    - echo $GOPATH
    - export PATH=$PATH:$HOME/bin:$GOPATH/bin
    - rm -rf $deploy_dir || exit 0

script:
    - gulp minifyStylesheets
    - gulp minifyScripts
    - hugo
    - gulp minifyHtml
    - cp Web.config public/Web.config
	- cp search.xml public/search.xml

branches:
  only:
    - master

after_success:
    - cp .travis.yml $git_deploy_dir
    - bash travisdeploy.sh --message "Travis auto commit "