language: go

before_install:
    - cd Sites/rahulrai

install: go get -v github.com/spf13/hugo

script:
    - hugo --theme=hugo_theme_robust -v

before_deploy:
    - git add public/*

branches:
  only:
    - master

deploy:
  provider: azure_web_apps
  verbose: true
  local-dir: public
  skip_cleanup: true