language: go

before_install:
    - cd Sites/rahulrai

install: go get -v github.com/spf13/hugo

script:
    - hugo --theme=hugo_theme_robust -v

deploy:
  provider: azure_web_apps
  on: 
    branch: master
  verbose: true

after_success:
    - echo "Deployed"