language: go

install: 
    - go get -v github.com/spf13/hugo
    - gem install dpl

script:
    - hugo --theme=hugo_theme_robust -v
    - git add public/*

branches:
  only:
    - master

after_success:
    - git remote add azure https://betablog:rahulBlog@betablogapp1.scm.azurewebsites.net:443/betablogapp1.git        
    - git push azure master --force --verbose 