language: go

sudo: required

install: 
    - go get -v github.com/spf13/hugo
    - gem install dpl
    - sudo apt-get install ncftp

script:
    - hugo --theme=hugo_theme_robust -v

branches:
  only:
    - master

after_success:
    - ncftpput -R -v -u "rahulrai" -p "TestCredentials" ftp://waws-prod-sn1-043.ftp.azurewebsites.windows.net /site /public