language: go

install: 
    - go get -v github.com/spf13/hugo
    - gem install dpl

script:
    - hugo --theme=hugo_theme_robust -v

branches:
  only:
    - master

after_success:
    - git add public/*
    - dpl --provider=AzureWebApps --username=betablog --password=India@123 --site=betablogapp1 --verbose