language: go

install: 
    - npm install gulp
    - npm install gulp-cssmin
    - npm install gulp-rename
    - npm install event-stream
    - npm install gulp-htmlmin
    - npm install gulp-uglify
    - go get -v github.com/spf13/hugo
    - rm -rf $deploy_dir || exit 0

script:
    - gulp minifyStylesheets
    - gulp minifyScripts
    - hugo
    - gulp minifyHtml
    - cp Web.config public/Web.config

branches:
  only:
    - master

after_success:
    - cp .travis.yml $git_deploy_dir
    - bash travisdeploy.sh --message "Travis auto commit "