baseurl = "http://betablogweb.azurewebsites.net/"
languageCode = "en-us"
title = "My Take on Cloud"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

#Hugo Defaults Override
disableHugoGeneratorInject = true
enableEmoji = true
disablePathToLower = true
theme = "hugo-phlat-theme"
paginate = 15

[blackfriday]
	hrefTargetBlank = false

[author]
    name = "Rahul Rai"
    email = "rahulrai@rahulrai.in"

#Theme Variables
[params]
    keywords            = ["Azure", "Cloud"]
    description         = "Let's explore this cool tech."
    google_analytics    = "UA-XXXXX-YY"
    google_adsense      = "Not Supported"
    disqus              = "shortname"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = "http://cdn.rahulrai.in/resources/siteIcon.png"
    resourcesBaseUrl    = "http://cdn.rahulrai.in/resources"
    contentBaseUrl      = "http://cdn.rahulrai.in/media"

# Social media icons and links that appear in the footer
[social]
    twitter             = "https://twitter.com/MoonyTheLoony"
    linkedin            = "https://in.linkedin.com/in/rahulrahul"
    email               = "mailto:rahulrai@rahulrai.in"
    facebook            = "https://www.facebook.com/moonytheloony"
    msdn                = "https://social.msdn.microsoft.com/profile/rahul.rai/"
    github              = "https://github.com/moonytheloony"
    skype               = "rahul.rai1986?call"

[permalinks]
    post = "/post/:slug"
    other = "/:slug"

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.header]]
    name = "blog"
    weight = 1
    url = "/"

[[menu.header]]
    name = "archive"
    weight = 2
    url = "/archive/"

[[menu.header]]
    name = "profile"
    weight = 3
    url = "/profile/"

[[menu.header]]
    name = "contact"
    weight = 4
    url = "/contact/"

[[menu.header]]
    name = "rss"
    weight = 5
    url = "/post/index.xml"

[[menu.footer]]
    name = "DISCLAIMER"
    weight = 1
    url = "/disclaimer/"