baseurl = "http://betablogweb.azurewebsites.net/"
languageCode = "en-us"
title = "My Take on Cloud"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

#Hugo Defaults Override
disableHugoGeneratorInject = true
enableEmoji = true
disablePathToLower = true
theme = "hugo-phlat-theme"
paginate = 1

[blackfriday]
	hrefTargetBlank = false

[author]
    name = "Rahul Rai"
    email = "rahulrai@rahulrai.in"

#Theme Variables
[params]
    keywords            = ["Azure", "Cloud"]
    description         = "Let's explore this cool tech."
    google_analytics    = "UA-XXXXX-YY"
    google_adsense      = "Not Supported"
    disqus              = "shortname"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = ""

# Social media icons and links that appear in the footer
[social]
    twitter             = "https://www.twitter.com/NAME_HERE"
    googleplus          = "https://plus.google.com/NAME_HERE"
    linkedin            = "https://www.linkedin.com/in/NAME_HERE"
    youtube             = "https://www.youtube.com/users/NAME_HERE"
    paypal              = "https://paypal.me/NAME_HERE"
    instagram           = ""
    reddit              = ""
    email               = ""
    pinterest           = ""
    wordpress           = ""

[permalinks]
    post = "/post/:slug"
    other = "/:slug"

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.header]]
    name = "Blog"
    weight = 1
    url = "/"

[[menu.header]]
    name = "blog archive"
    weight = 2
    url = "/archive/"

[[menu.header]]
    name = "profile"
    weight = 3
    url = "/profile/"

[[menu.header]]
    name = "curriculum vitae"
    weight = 4
    url = "/cv/"

[[menu.header]]
    name = "RSS"
    weight = 5
    url = "/post/index.xml"

[[menu.footer]]
    name = "Disclaimer"
    weight = 1
    url = "/disclaimer/"