baseurl = "https://rahulrai.in/"
languageCode = "en-us"
title = "My Take on Cloud"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
disableHugoGeneratorInject = true
enableEmoji = true
disablePathToLower = true
theme = "hugo-phlat-theme"
paginate = 15

[blackfriday]
	hrefTargetBlank = false

[sitemap]
	changefreq = "always"
	priority = 1
	filename = "sitemap"

[author]
    name = "Rahul Rai"
    email = "rahulrai@rahulrai.in"

#Theme Variables
[params]
    keywords = ["Azure", "Cloud"]
    description = "Let's explore this cool tech."
	heapAnalytics = "2215857163"
	appInsights = "963f772c-0ccc-4148-8dd0-d592c04d6d7b"
    disqus = "rahulrai"
    google_webmaster = "QCQmaQxL8c2x6yrpUDr91jfBZNSpexndMkeOqZPFlqM"
    bing_webmaster = "F6575BFCC1322FDFE66EA304BDB69F33"
	googleSearchId = "017749396232577371525:uclf-xfot8k"
    favicon = "https://rahulrai.azureedge.net/resources/siteIcon.png"
    resourcesBaseUrl = "https://rahulrai.azureedge.net/resources"
    contentBaseUrl = "https://rahulrai.azureedge.net/media"
	
# Social media icons and links that appear in the footer
[social]
    twitter = "https://twitter.com/MoonyTheLoony"
    linkedin = "https://in.linkedin.com/in/rahulrahul"
    email = "mailto:rahulrai@rahulrai.in"
    facebook = "https://www.facebook.com/moonytheloony"
    msdn = "https://social.msdn.microsoft.com/profile/rahul.rai/"
    github = "https://github.com/moonytheloony"
    skype = "rahul.rai1986?call"

[permalinks]
    post = "/post/:slug"
    other = "/:slug"

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.header]]
    name = "blog"
    weight = 1
    url = "/"

[[menu.header]]
    name = "archive"
    weight = 2
    url = "/archive/"

[[menu.header]]
    name = "profile"
    weight = 3
    url = "/profile/"

[[menu.header]]
    name = "contact"
    weight = 4
    url = "/contact/"

[[menu.header]]
    name = "rss"
    weight = 5
    url = "/post/index.xml"

[[menu.footer]]
    name = "DISCLAIMER"
    weight = 1
    url = "/disclaimer/"